import type { CosmeticDefinition } from './types';
import { EXPANSION_AVATARS } from './expansion';

const LEGACY_COSMETICS: readonly Omit<CosmeticDefinition, 'kind' | 'modelFamily'>[] = Object.freeze([
  {
    id: 'gold',
    name: 'Gold',
    description: 'A golden bath-time classic.',
    starter: true,
    category: null,
    color: '#efc64c',
    accentColor: '#fff1a5',
    beakColor: '#dc8627',
    metalness: 0.85,
    roughness: 0.2,
    pattern: 'solid',
  },
  {
    id: 'yellow',
    name: 'Yellow',
    description: 'The original sunny little duck.',
    starter: true,
    category: null,
    color: '#ffd91a',
    accentColor: '#fff8c0',
    beakColor: '#f28b08',
    metalness: 0.02,
    roughness: 0.28,
    pattern: 'solid',
  },
  {
    id: 'pink',
    name: 'Pink',
    description: 'A rosy splash of color.',
    starter: true,
    category: null,
    color: '#ed8bb9',
    accentColor: '#ffd2e7',
    beakColor: '#f19146',
    metalness: 0.02,
    roughness: 0.28,
    pattern: 'solid',
  },
  {
    id: 'mint',
    name: 'Mint',
    description: 'Fresh mint for the pool.',
    starter: true,
    category: null,
    color: '#84d9b5',
    accentColor: '#caffdf',
    beakColor: '#ed9652',
    metalness: 0.02,
    roughness: 0.28,
    pattern: 'solid',
  },
  {
    id: 'tangerine',
    name: 'Tangerine',
    description: 'Earn all three Collection bronze medals.',
    starter: false,
    category: 'collection',
    color: '#ff9a30',
    accentColor: '#ffeab3',
    beakColor: '#ef592e',
    metalness: 0.02,
    roughness: 0.28,
    pattern: 'solid',
  },
  {
    id: 'pearl',
    name: 'Pearl',
    description: 'Earn all three Rescue bronze medals.',
    starter: false,
    category: 'rescue',
    color: '#e8f6ef',
    accentColor: '#c5e9ff',
    beakColor: '#e9a45c',
    metalness: 0.22,
    roughness: 0.2,
    pattern: 'pearl',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Earn all three Practice Skill bronze medals.',
    starter: false,
    category: 'practice',
    color: '#bda4ff',
    accentColor: '#dfceff',
    beakColor: '#efaa62',
    metalness: 0.02,
    roughness: 0.28,
    pattern: 'solid',
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    description: 'Earn all three Growth bronze medals.',
    starter: false,
    category: 'growth',
    color: '#3374d8',
    accentColor: '#97d6ff',
    beakColor: '#ffae45',
    metalness: 0.15,
    roughness: 0.24,
    pattern: 'solid',
  },
  {
    id: 'cherry',
    name: 'Cherry',
    description: 'Earn all three Combat bronze medals.',
    starter: false,
    category: 'combat',
    color: '#db4065',
    accentColor: '#ffbdcc',
    beakColor: '#ffc168',
    metalness: 0.04,
    roughness: 0.24,
    pattern: 'solid',
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    description: 'Earn all three Flock Control bronze medals.',
    starter: false,
    category: 'control',
    color: '#f680be',
    accentColor: '#bceeff',
    beakColor: '#ffb657',
    metalness: 0.05,
    roughness: 0.24,
    pattern: 'pearl',
  },
  {
    id: 'chrome',
    name: 'Chrome',
    description: 'Earn all three Sharks bronze medals.',
    starter: false,
    category: 'sharks',
    color: '#dbe6f5',
    accentColor: '#8397bd',
    beakColor: '#c4d3e9',
    metalness: 1,
    roughness: 0.14,
    pattern: 'solid',
  },
  {
    id: 'starry',
    name: 'Starry',
    description: 'Earn all three Endurance bronze medals.',
    starter: false,
    category: 'endurance',
    color: '#33437b',
    accentColor: '#fff0a1',
    beakColor: '#ffd776',
    metalness: 0.12,
    roughness: 0.28,
    pattern: 'stars',
  },
  {
    id: 'koi',
    name: 'Koi',
    description: 'Earn two silver category mastery badges.',
    starter: false,
    category: null,
    silverMasteries: 2,
    color: '#fff1d9',
    accentColor: '#e4612a',
    beakColor: '#e9a13d',
    metalness: 0,
    roughness: 0.29,
    pattern: 'koi',
  },
  {
    id: 'porcelain',
    name: 'Porcelain',
    description: 'Earn four silver category mastery badges.',
    starter: false,
    category: null,
    silverMasteries: 4,
    color: '#f4f6f2',
    accentColor: '#285c9b',
    beakColor: '#e9b85c',
    metalness: 0,
    roughness: 0.19,
    pattern: 'porcelain',
  },
  {
    id: 'sailor',
    name: 'Sailor',
    description: 'Earn six silver category mastery badges.',
    starter: false,
    category: null,
    silverMasteries: 6,
    color: '#e9eff4',
    accentColor: '#193b68',
    beakColor: '#eda643',
    metalness: 0,
    roughness: 0.34,
    pattern: 'sailor',
  },
  {
    id: 'copper',
    name: 'Copper',
    description: 'Earn eight silver category mastery badges.',
    starter: false,
    category: null,
    silverMasteries: 8,
    color: '#b96d42',
    accentColor: '#59a38f',
    beakColor: '#9c532d',
    metalness: 0.93,
    roughness: 0.3,
    pattern: 'copper',
  },
]);

export const COSMETICS: readonly CosmeticDefinition[] = Object.freeze([
  ...LEGACY_COSMETICS.map((item) =>
    Object.freeze({ ...item, kind: 'avatar' as const, modelFamily: 'duck' as const }),
  ),
  ...EXPANSION_AVATARS,
]);
