import type { CosmeticCategory } from '@supadub/cosmetics';
import type { Metric, MetricAchievementDefinition } from './types';
import { EXPANSION_ACHIEVEMENTS } from './expansion';

function entry(
  id: string,
  name: string,
  description: string,
  category: CosmeticCategory,
  metric: Metric,
  aggregation: MetricAchievementDefinition['aggregation'],
  thresholds: MetricAchievementDefinition['thresholds'],
  unit: MetricAchievementDefinition['unit'],
  modes: MetricAchievementDefinition['modes'] = ['endless'],
): MetricAchievementDefinition {
  return Object.freeze({
    kind: 'metric',
    id,
    name,
    description,
    category,
    metric,
    aggregation,
    thresholds: Object.freeze(thresholds),
    unit,
    modes: Object.freeze(modes),
  });
}

export const LEGACY_METRIC_ACHIEVEMENTS: readonly MetricAchievementDefinition[] = Object.freeze([
  entry(
    'natural-ducks',
    'Duck Collector',
    'Collect natural ducklings in the Endless pool.',
    'collection',
    'naturalDucks',
    'sum',
    [25, 250, 2500],
    'ducks',
  ),
  entry(
    'run-collector',
    'A Busy Bath',
    'Collect ducklings during one Endless run.',
    'collection',
    'runDucks',
    'max',
    [25, 100, 500],
    'ducks',
  ),
  entry(
    'quick-collector',
    'Quick Quacks',
    'Collect ducklings within any sixty seconds.',
    'collection',
    'quickDucks',
    'max',
    [10, 30, 60],
    'ducks',
  ),
  entry(
    'ducks-saved',
    'To the Rescue',
    'Lead ducklings through the Practice exit.',
    'rescue',
    'savedDucks',
    'sum',
    [12, 120, 1200],
    'ducks',
    ['practice'],
  ),
  entry(
    'practice-finisher',
    'Tub Finisher',
    'Complete Practice tubs.',
    'rescue',
    'practiceRuns',
    'sum',
    [1, 10, 100],
    'runs',
    ['practice'],
  ),
  entry(
    'duck-chain',
    'All in a Row',
    'Deliver a long chain at the Practice exit.',
    'rescue',
    'deliveredChain',
    'max',
    [4, 8, 12],
    'ducks',
    ['practice'],
  ),
  entry(
    'speed-rescue',
    'Splash in a Flash',
    'Finish Practice within the adjusted time.',
    'practice',
    'practiceTimeMs',
    'min',
    [25000, 15000, 8000],
    'milliseconds',
    ['practice'],
  ),
  entry(
    'single-chain',
    'One Big Family',
    'Save every duck in a single delivered chain.',
    'practice',
    'singleChainRuns',
    'sum',
    [1, 10, 50],
    'runs',
    ['practice'],
  ),
  entry(
    'completion-streak',
    'Keep Splashing',
    'Complete tubs without abandoning an unfinished run.',
    'practice',
    'completionStreak',
    'max',
    [3, 10, 25],
    'runs',
    ['practice'],
  ),
  entry(
    'body-mass',
    'Big Ducky',
    'Grow one duck to the target mass.',
    'growth',
    'bodyMass',
    'max',
    [500, 5000, 22500],
    'mass',
  ),
  entry(
    'flock-mass',
    'A Mighty Flock',
    'Reach the target total mass in one run.',
    'growth',
    'totalMass',
    'max',
    [1000, 10000, 50000],
    'mass',
  ),
  entry(
    'fast-growth',
    'Growing Fast',
    'Reach the target mass in the first two minutes.',
    'growth',
    'fastMass',
    'max',
    [500, 1500, 5000],
    'mass',
  ),
  entry(
    'body-absorber',
    'Pool Rival',
    'Absorb bodies from other human players.',
    'combat',
    'absorptions',
    'sum',
    [10, 100, 1000],
    'bodies',
  ),
  entry(
    'pool-champion',
    'Last Duck Floating',
    'Absorb the final body of another human player.',
    'combat',
    'eliminations',
    'sum',
    [1, 25, 250],
    'runs',
  ),
  entry(
    'split-absorber',
    'Perfect Splash',
    'Absorb other human bodies during a manual split launch.',
    'combat',
    'splitAbsorptions',
    'sum',
    [1, 25, 100],
    'bodies',
  ),
  entry(
    'full-flock',
    'More the Merrier',
    'Control several duck bodies at once.',
    'control',
    'bodyCount',
    'max',
    [4, 8, 16],
    'bodies',
  ),
  entry(
    'split-master',
    'Make a Splash',
    'Use successful manual split actions.',
    'control',
    'splitActions',
    'sum',
    [10, 100, 1000],
    'actions',
  ),
  entry(
    'reunion',
    'Together Again',
    'Merge your ducks after their cooldown.',
    'control',
    'reunions',
    'sum',
    [10, 100, 500],
    'actions',
  ),
  entry(
    'shark-feeder',
    'Snack Time',
    'Feed ejected pellets to sharks.',
    'sharks',
    'pelletsFed',
    'sum',
    [7, 70, 700],
    'actions',
  ),
  entry(
    'shark-launcher',
    'Shark Splash',
    'Trigger a shark launch with seven pellets.',
    'sharks',
    'sharkLaunches',
    'sum',
    [1, 10, 100],
    'actions',
  ),
  entry(
    'shark-survivor',
    'Still Floating',
    'Survive ten seconds after a shark burst.',
    'sharks',
    'sharkSurvivals',
    'sum',
    [1, 10, 100],
    'actions',
  ),
  entry(
    'long-swim',
    'Long Bath',
    'Stay alive in one Endless run.',
    'endurance',
    'runDurationMs',
    'max',
    [120000, 600000, 1800000],
    'milliseconds',
  ),
  entry(
    'distance-swimmer',
    'Pool Explorer',
    'Swim through the Endless pool.',
    'endurance',
    'distance',
    'sum',
    [1000, 10000, 100000],
    'units',
  ),
  entry(
    'generous-duck',
    'Share a Splash',
    'Donate ejected mass to other human players.',
    'endurance',
    'donatedMass',
    'sum',
    [200, 2000, 20000],
    'mass',
  ),
]);

export const METRIC_ACHIEVEMENTS: readonly MetricAchievementDefinition[] = Object.freeze([
  ...LEGACY_METRIC_ACHIEVEMENTS,
  ...EXPANSION_ACHIEVEMENTS,
]);
