import type { CosmeticCategory } from '@supadub/cosmetics';
import type { Metric, MetricAchievementDefinition } from './types';

function achievement(
  id: string,
  name: string,
  description: string,
  category: CosmeticCategory,
  metric: Metric,
  aggregation: 'sum' | 'max',
  thresholds: readonly [number, number, number],
  unit: MetricAchievementDefinition['unit'],
  modes: MetricAchievementDefinition['modes'] = ['endless'],
): MetricAchievementDefinition {
  return Object.freeze({
    id,
    name,
    description,
    category,
    metric,
    aggregation,
    thresholds: Object.freeze(thresholds),
    unit,
    modes: Object.freeze(modes),
    kind: 'metric',
  });
}

export const EXPANSION_ACHIEVEMENTS: readonly MetricAchievementDefinition[] = Object.freeze([
  achievement(
    'charted-pool',
    'Chart the Pool',
    'Visit different pool chunks in one run.',
    'exploration',
    'chartedChunks',
    'max',
    [4, 16, 64],
    'units',
  ),
  achievement(
    'distant-shores',
    'Distant Shores',
    'Travel far from your spawn in one run.',
    'exploration',
    'farthestDistance',
    'max',
    [128, 512, 2048],
    'units',
  ),
  achievement(
    'feeding-grounds',
    'Feeding Grounds',
    'Collect natural ducklings in different chunks during one run.',
    'exploration',
    'feedingChunks',
    'max',
    [3, 12, 48],
    'units',
  ),
  achievement(
    'careful-deliveries',
    'Careful Deliveries',
    'Deliver chains of at least four ducklings.',
    'rescue-craft',
    'deliveries',
    'sum',
    [3, 30, 150],
    'actions',
    ['practice'],
  ),
  achievement(
    'prompt-deliveries',
    'Prompt Deliveries',
    'Deliver at least four ducklings within ten seconds of the previous delivery or run start.',
    'rescue-craft',
    'promptDeliveries',
    'sum',
    [1, 15, 75],
    'actions',
    ['practice'],
  ),
  achievement(
    'efficient-rescue',
    'Neat Rescue',
    'Finish a tub with no more than 120 units of travel.',
    'rescue-craft',
    'efficientRescues',
    'sum',
    [1, 10, 50],
    'runs',
    ['practice'],
  ),
  achievement(
    'distant-feeding',
    'Long Toss',
    'Feed sharks with pellets that travel at least six units.',
    'shark-tactics',
    'distantFeeds',
    'sum',
    [7, 70, 350],
    'actions',
  ),
  achievement(
    'burst-recovery',
    'Back Together',
    'Keep flock mass for ten seconds after a shark burst.',
    'shark-tactics',
    'burstRecoveryMass',
    'max',
    [250, 1000, 5000],
    'mass',
  ),
  achievement(
    'shark-harvest',
    'Shark Snacks',
    'Collect mass from shark contact.',
    'shark-tactics',
    'sharkHarvestMass',
    'sum',
    [300, 3000, 15000],
    'mass',
  ),
  achievement(
    'shared-snacks',
    'Snacks for All',
    'Eject from several bodies in one action.',
    'flock-craft',
    'simultaneousEjections',
    'max',
    [2, 8, 16],
    'bodies',
  ),
  achievement(
    'flock-voyage',
    'Flock Voyage',
    'Travel while at least four bodies float together.',
    'flock-craft',
    'flockDistance',
    'sum',
    [250, 2500, 15000],
    'units',
  ),
  achievement(
    'balanced-flock',
    'Balanced Flock',
    'Grow every body in a flock of four or more.',
    'flock-craft',
    'balancedBodyMass',
    'max',
    [80, 500, 2500],
    'mass',
  ),
  achievement(
    'rival-mass',
    'Rival Collector',
    'Absorb mass from human rivals.',
    'rivalry',
    'humanMassAbsorbed',
    'sum',
    [500, 5000, 25000],
    'mass',
  ),
  achievement(
    'rival-streak',
    'Pool Streak',
    'Eliminate human rivals during one run.',
    'rivalry',
    'runEliminations',
    'max',
    [2, 5, 15],
    'runs',
  ),
  achievement(
    'comeback-flock',
    'Comeback Flock',
    'Reach flock mass after losing a body to a human rival.',
    'rivalry',
    'comebackMass',
    'max',
    [250, 1500, 7500],
    'mass',
  ),
  achievement(
    'wardrobe-tour',
    'Wardrobe Tour',
    'Use different avatars for ten seconds or a complete rescue.',
    'collection-craft',
    'avatarsUsed',
    'max',
    [2, 8, 16],
    'units',
    ['endless', 'practice'],
  ),
  achievement(
    'dressed-traveler',
    'Dressed Traveler',
    'Travel with at least two equipped accessories.',
    'collection-craft',
    'adornedDistance',
    'sum',
    [250, 2500, 10000],
    'units',
    ['endless', 'practice'],
  ),
  achievement(
    'earned-collection',
    'Toy Collector',
    'Earn new toys and items through achievements.',
    'collection-craft',
    'earnedItems',
    'max',
    [6, 18, 36],
    'units',
    ['endless', 'practice'],
  ),
]);
